<?php
return [
    'engine_idle' => 'Parado Ignição Ligada',
    'dis_h_km' => 'km/h',
    'objects' => 'Veículo(s)',
    'object_groups' => 'Grupos de Veículo(s)',
    'object_listview' => 'Lista de Veículo(s)',
    'fit_objects' => 'Ajustar Veículo(s)',
    'object_history' => 'Histórico de Posição do Veículo',
    'object_history_report' => 'Relatório de histórico de  Veículo(s)',
    'offline_objects' => 'Veículo(s) off-line',
    'offline_objects_report' => 'Relatório de Veículo(s) offline',
    'maximum_of_objects' => 'O número máximo de Veículo(s)  disponíveis',
    'installation_all_objects' => 'Instalação de Veículo(s)',
    'installation_offline_objects' => 'Instalação de Veículo(s)  offline',
    'create_only_expired_objects' => 'Crie apenas Veículo(s) expirados',
    'devices_limit_reached' => 'Limite máximo de Veículo(s) .',
    'no_devices_with_sim_number' => 'Você não tem os Veículo(s)  com o "Número SIM" para enviar sms. "Número SIM" pode ser adicionado em: Objeto->Editar->Avançado->número SIM.',
    'import_devices' => 'Importar Veículo(s) .',
    'devices_activity_percents' => 'Veículo(s)  (porcentagens)',
    'all_devices' => 'Todos os Veículo(s)',
    'devices' => 'Veículo(s)',
    'kph' => 'Km/h',
    'subscribe' => 'Assinar',
    'zone_in' => 'Entrou na Cerca',
    'overspeed' => 'Excesso de Velocidade',
    'show_history' => 'Mostrar Histórico',
    'no_map_icons' => 'Nenhum ícone de Mapa.',
    'detailed_report' => 'Relatório Detalhado',
];
